version: '3.8'

services:
  tts-app:
    container_name: tts-home-server
    build: .
    ports:
      - "8501:8501"
    restart: unless-stopped
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false --browser.gatherUsageStats=false
